version: 0.2


stages:
  assemble: # commands run by manager (e.g. packaging, cross-compilation)
    - make
    - make clean
  transfer: # list of files and directories copied to targets
    - package/monitor
    - package/rescue
    - package/rescue.json
    - package/monitor.json
    - package/test-script.sh
  install: # commands run by agent
    - chmod +x package/monitor
    - chmod +x package/rescue
  test:
    - sh test-script.sh
  activate:
    - on-success # when tests pass
    - on-startup
    - manually # signal from AL or Command & Monitoring Tool (CMT)

target:
  byname:
    - dummy1
    - pi* # wildcard matching
  bytype:
    - pizero
    - turtlebot

log:
  - always
  - on-failure # tests / stages fail
  - on-success # output of stage command regardless