version: 0.4

# Deployment stages
stages:
  # commands run locally by the manager (e.g. packaging, cross-compilation)
  assemble:
    - make
    - make clean
  # list of files and directories copied to targets
  transfer:
    - package
  # commands run on target devices
  install:
    - mv package/dummy.py package/app.py
  # validation tests
  test:
    - sh test-script.sh
  # package execution on target devices
  run:
    - python -u package/app.py

# Which target devices should receive the package
target:
  tags:
    - groupA
    - turtlebot

# How target devices report logs
log:
  interval: 3s
  verbosity: DEBUG
  # The following verbosity levels are supported:
  # ERROR: stderr of stages
  # INFO: ERROR and stdout stages
  # DEBUG: INFO and agent internal logs
